services:
  coolify-badge:
    build: .
    container_name: coolify-badge-service
    restart: always
    environment:
      - COOLIFY_API_URL=${COOLIFY_API_URL}
      - API_TOKEN=${API_TOKEN}
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"

    read_only: true
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: "0.1"
    healthcheck:
      test: ["CMD-SHELL", "sleep 0"]
      interval: 30s
      timeout: 5s
      retries: 3
